### ISSUE TITLE
Uncaught Error: Could not parse row Warning: React version not specified in eslint-plu...

### ISSUE THREAD

**Issue by Vlad78** [AtomLinter/linter-eslint-node#20]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.60.0 x64
**Electron**: 9.4.4
**OS**: �������� Windows 10 �������
**Thrown From**: [linter-eslint-node](https://github.com/AtomLinter/linter-eslint-node) package 1.0.5

### Stack Trace

Uncaught Error: Could not parse row Warning: React version not specified in eslint-plu...

```
At events.js:200

Error: Could not parse row Warning: React version not specified in eslint-plu...
    at /packages/linter-eslint-node/node_modules/ndjson/index.js:20:28)
    at /packages/linter-eslint-node/node_modules/split2/index.js:44:23)
    at Transform._read (/packages/linter-eslint-node/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at Transform._write (/packages/linter-eslint-node/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/packages/linter-eslint-node/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/packages/linter-eslint-node/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Transform.Writable.write (/packages/linter-eslint-node/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Socket.ondata (_stream_readable.js:728:22)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

### Commands

```
     -0:38.1.0 typescript:activate (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.3 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-javascript 1.5.0 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
atom-typescript 14.4.0 
autocomplete-javascript 0.0.2 
autocomplete-paths undefined 
busy-signal 2.0.1 
darcula-syntax 0.2.1 
emmet-jsx-css-modules 1.0.0 
insales-javascript-snippets 0.7.1 
insales-liquid-snippets 0.12.0 
insales-lodash-snippets 0.4.0 
intentions 2.1.1 
javascript-drag-import 0.1.13 
language-babel 2.85.0 
language-javascript-jsx 0.3.7 
language-liquid-insales 0.8.0 
linter 3.4.0 
linter-eslint 9.0.1 
linter-eslint-node 1.0.5 
linter-ui-default 3.4.1 
prettier-atom 0.60.1 
react 0.18.0 
react-snippets 2.0.0 
turbo-javascript 1.4.0 
```

**Comment by savetheclocktower** [comment]
Can you fill out the entire issue template, please? Otherwise we won't know how to reproduce the issue. Thanks!

**Comment by Naxit** [comment]
> Can you fill out the entire issue template, please? Otherwise we won't know how to reproduce the issue. Thanks!

Hi there, 

I will try to fill out the template, as I have the same issue on macOS:
![image](https://user-images.githubusercontent.com/15122761/163827319-422b073f-4179-4f10-8a3c-b1904f207e47.png)

Atom version : 
![image](https://user-images.githubusercontent.com/15122761/163827380-2fc9deec-33bb-4678-82a8-a0ac5b1d3343.png)

Steps to reproduce : 
- open Atom.
- I saw this error :
![image](https://user-images.githubusercontent.com/15122761/163827252-90e366ed-ad76-459f-8750-fb847c1a2212.png)

Expected behavior : Atom open without any error
Actual behavior : Atom opens with the reported error

I clicked on the "View issue" button and ended up here :)

**Comment by savetheclocktower** [comment]
Thanks, @naxit. I'd be interested to see your `.eslintrc`, as that'd possibly give me enough information to reproduce this problem.

**Comment by Naxit** [comment]
@savetheclocktower I guess my project use some global configuration file because I don't have any `.eslintrc` file in the project which was opened on the Atom instance that throwed this error. 
How can I give you the informations you may need, then ?

**Comment by EvHaus** [comment]
Not sure if it's related but I'm getting this error:

```
Error: Could not parse row (node:71572) Warning: Accessing non-existent prope...
    at Transform.parseRow [as mapper] (/Users/evhaus/.atom/packages/linter-eslint-node/node_modules/ndjson/index.js:20:28)
    at Transform.transform [as _transform] (/Users/evhaus/.atom/packages/linter-eslint-node/node_modules/split2/index.js:44:23)
    at Transform._read (/Users/evhaus/.atom/packages/linter-eslint-node/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at Transform._write (/Users/evhaus/.atom/packages/linter-eslint-node/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/Users/evhaus/.atom/packages/linter-eslint-node/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/Users/evhaus/.atom/packages/linter-eslint-node/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Transform.Writable.write (/Users/evhaus/.atom/packages/linter-eslint-node/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Socket.ondata (_stream_readable.js:716:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by bsbechtel** [comment]
@savetheclocktower I can't seem to find version 1.0.6 in the Atom Package Manager. Was it released for download?
