### ISSUE TITLE
Uncaught Error: Could not parse row The prop value with an expression type of JSXEmpty...

### ISSUE THREAD

**Issue by maxelston** [AtomLinter/linter-eslint-node#32]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.60.0 x64
**Electron**: 9.4.4
**OS**: macOS 12.4
**Thrown From**: [linter-eslint-node](https://github.com/AtomLinter/linter-eslint-node) package 1.0.5

### Stack Trace

Uncaught Error: Could not parse row The prop value with an expression type of JSXEmpty...

```
At events.js:200

Error: Could not parse row The prop value with an expression type of JSXEmpty...
    at /packages/linter-eslint-node/node_modules/ndjson/index.js:20:28)
    at /packages/linter-eslint-node/node_modules/split2/index.js:44:23)
    at Transform._read (/packages/linter-eslint-node/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at Transform._write (/packages/linter-eslint-node/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/packages/linter-eslint-node/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/packages/linter-eslint-node/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Transform.Writable.write (/packages/linter-eslint-node/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Socket.ondata (_stream_readable.js:728:22)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

### Commands

```
  2x -0:45.1.0 editor:newline (input.hidden-input)
     -0:44.8.0 core:move-right (input.hidden-input)
     -0:43.9.0 core:move-up (input.hidden-input)
     -0:43.6.0 intentions:highlight (input.hidden-input)
     -0:43.5.0 core:paste (input.hidden-input)
     -0:43.2.0 core:move-up (input.hidden-input)
     -0:42.7.0 core:backspace (input.hidden-input)
     -0:41.8.0 core:move-down (input.hidden-input)
     -0:41.2.0 core:backspace (input.hidden-input)
     -0:39.1.0 intentions:highlight (input.hidden-input)
  4x -0:38.8.0 core:copy (input.hidden-input)
     -0:37.7.0 intentions:highlight (input.hidden-input)
     -0:37.6.0 core:paste (input.hidden-input)
     -0:36.5.0 intentions:highlight (input.hidden-input)
     -0:36.4.0 core:save (input.hidden-input)
     -0:05.6.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
busy-signal 2.0.1 
ide-typescript 0.9.5 
intentions 2.1.1 
linter 3.4.0 
linter-eslint 9.0.1 
linter-eslint-node 1.0.5 
linter-tslint 1.11.1 
linter-ui-default 3.4.1 
```

**Comment by scagood** [comment]
🤔 Do you have a link to a repo this happens with?
Or maybe a minimal example of the ieeus?
